---
###############################################################################
# Configure Services
###############################################################################
# Use UID/GID as filesystems may be remote. Permissions are determined from Mox
# install - Mox will set correct permissions on startup.
#
# Mox service starts as root and drops privileges once network sockets are
# opened.
#
# Reference:
# * https://www.xmox.nl/config/

- name: 'Config | manage storage directories'
  ansible.builtin.file:
    path: '{{ item }}'
    owner: '{{ _mox_srv_user._uid }}'
    group: '{{ _mox_srv_group._gid }}'
    mode: '2750'
    state: 'directory'
  loop:
    - '{{ _mox_srv_storage_dir._data }}'
    - '{{ _mox_srv_storage_dir._config }}'
    - '{{ _mox_srv_storage_dir._web }}'
  become: true
  become_user: '{{
      _mox_srv_user.raw
      if _mox_srv_user_data_manage_enable.raw else
      "root"
    }}'

- name: 'Config | manage web directories'
  ansible.builtin.file:
    path: '{{ item }}'
    owner: '{{ _mox_srv_user._uid }}'
    group: '{{ _mox_srv_group._gid }}'
    mode: '0750'
    state: 'directory'
  loop:
    - '{{ _mox_srv_storage_dir._data }}'
    - '{{ _mox_srv_storage_dir._config }}'
    - '{{ _mox_srv_storage_dir._web }}'
  become: true
  become_user: '{{
      _mox_srv_user.raw
      if _mox_srv_user_data_manage_enable.raw else
      "root"
    }}'

- name: 'Config | import from controller'
  when: _mox_srv_import_config.raw | length > 0
  ansible.posix.synchronize:
    src: '{{ _mox_srv_import_config._src }}'
    dest: '{{ _mox_srv_storage_dir._config }}'
    delete: true
    recursive: true
    archive: false
    checksum: true

# yamllint disable rule:line-length
- name: 'Config | set permissions'
  when: _mox_srv_import_config.raw | length > 0
  ansible.builtin.shell: >-
    chown -R {{ _mox_srv_user._uid }}:{{ _mox_srv_group._gid }} '{{ _mox_srv_storage_dir._config }}' &&
    find '{{ _mox_srv_storage_dir._config }}' -type d -exec chmod 0750 {} \; &&
    find '{{ _mox_srv_storage_dir._config }}' -type f -exec chmod 0640 {} \;
  args:
    executable: '/bin/bash'
  changed_when: false
# yamllint enable rule:line-length

- name: 'Config | set service definitions'
  ansible.builtin.include_role:
    name: 'r_pufky.deb.systemd'
  vars:
    systemd_daemon_reload_enable: true
    systemd_services:
      - name: 'mox'
        state: 'present'
        drop_in: false
        unit:
          description: 'mox mail server'
          after:
            - 'network-online.target'
          wants:
            - 'network-online.target'
        service:
          u_mask: '007'
          limit_nofile: 65536
          type: 'simple'
          exec_start:
            - '{{ _mox_srv_storage_dir._bin ~ " serve" }}'
          exec_stop:
            - '{{ _mox_srv_storage_dir._bin ~ " stop" }}'
          restart_sec: '5s'
          restart: 'always'
          syslog_facility: 'mail'

        exec:
          working_directory: '{{ _mox_srv_storage_dir.raw }}'
          private_devices: true
          private_tmp: true
          protect_system: 'strict'
          read_write_paths:
            - '{{ _mox_srv_storage_dir._config }}'
            - '{{ _mox_srv_storage_dir._data }}'
          protect_kernel_tunables: true
          protext_control_groups: true
          ambient_capabilities:  # AmbientCapabilities=
            - ''
          capability_bounding_set:
            - 'CAP_SETUID'
            - 'CAP_SETGID'
            - 'CAP_NET_BIND_SERVICE'
            - 'CAP_CHOWN'
            - 'CAP_FSETID'
            - 'CAP_DAC_OVERRIDE'
            - 'CAP_DAC_READ_SEARCH'
            - 'CAP_FOWNER'
            - 'CAP_KILL'
          no_new_privileges: true
          restrict_address_families:
            - 'AF_INET'
            - 'AF_INET6'
            - 'AF_UNIX'
            - 'AF_NETLINK'
          protect_proc: 'invisible'
          restrict_namespaces: true
          restrict_realtime: true
          remove_ipc: true
          protect_hostname: true
          protect_clock: true
          protect_kernel_logs: true
          protect_kernel_modules: true
          memory_deny_write_execute: true
          lock_personality: true
          device_policy: 'closed'
          system_call_architectures:
            - 'native'
          system_call_filter: '@system-service'
        install:
          wanted_by:
            - 'multi-user.target'
