---
###############################################################################
# Default
###############################################################################
# Default and configuration set is deployed correctly. Do not valid user
# source config files, only that role applied them correctly.
#
# Tests:
# * Binary deployed correctly.
# * Mox service NOT active/running (mox-default).
# * Mox service active and running (mox-config).
# * Permissions propagated correctly.

dependency:
  name: 'galaxy'
driver:
  name: 'podman'
provisioner:
  name: 'ansible'
  config_options:
    defaults:
      interpreter_python: 'auto_silent'
      callback_whitelist: 'profile_tasks, timer, yaml'
    ssh_connection:
      pipelining: false
  inventory:
    host_vars:
      mox-config:
        mox_flg_config: true
        mox_cfg_d: '{{
            lookup("env", "MOLECULE_SCENARIO_DIRECTORY") ~ "/files/config"
          }}'
platforms:
  - name: 'mox-default'
    image: 'ghcr.io/hifis-net/debian-systemd:13'
    systemd: 'always'
    volumes:
      - '/sys/fs/cgroup:/sys/fs/cgroup:ro'
    command: '/lib/systemd/systemd'
    pre_build_image: true
  - name: 'mox-config'
    image: 'ghcr.io/hifis-net/debian-systemd:13'
    systemd: 'always'
    volumes:
      - '/sys/fs/cgroup:/sys/fs/cgroup:ro'
    command: '/lib/systemd/systemd'
    published_ports:
      - '8443:443/tcp'
    pre_build_image: true
verifier:
  name: 'ansible'
scenario:
  test_sequence:
    - 'destroy'
    - 'syntax'
    - 'create'
    - 'prepare'
    - 'converge'
    - 'verify'
    - 'destroy'
