---
###############################################################################
# Verify
###############################################################################
# Decision: SUID/SGID bits cannot be set by a standard user for 'root' - this
#     will result in errors during role application. Mox will correct
#     permissions on first run. This will lead differential in testing between
#     what is set in the role with user data enabled, and testing resultant
#     permissions for mox-config.
#
# See install.yml.

- name: 'Verify'
  hosts: 'all'
  gather_facts: false
  tasks:
    - name: 'Verify | import role variables'
      ansible.builtin.include_vars:
        file: '{{
            lookup("env", "MOLECULE_PROJECT_DIRECTORY") ~ "/vars/main.yml"
          }}'

    - name: '{{ "Verify | test | " ~ mox___app._bin }}'
      ansible.builtin.include_role:
        name: 'r_pufky.data.test'
        tasks_from: 'file.yml'
      vars:
        test_name: '{{ "Verify | test | " ~ mox___app._bin }}'
        test_file: '{{ mox___app._bin }}'
        test_owner: 'root'
        test_group: 'root'
        test_mode: '0755'
        test_state: 'file'
        test_diff: true

    - name: '{{ "Verify | test | " ~ mox___app._web_d }}'
      ansible.builtin.include_role:
        name: 'r_pufky.data.test'
        tasks_from: 'file.yml'
      vars:
        test_name: '{{ "Verify | test | " ~ mox___app._web_d }}'
        test_file: '{{ mox___app._web_d }}'
        test_owner: 'mox'
        test_group: 'mox'
        test_mode: '0750'
        test_state: 'directory'
        test_diff: true

- name: 'Verify'
  hosts: 'mox-default'
  gather_facts: false
  tasks:
    - name: 'Verify | import role variables'
      ansible.builtin.include_vars:
        file: '{{
            lookup("env", "MOLECULE_PROJECT_DIRECTORY") ~ "/vars/main.yml"
          }}'

    - name: '{{ "Verify | test | " ~ mox___app._var_d }}'
      ansible.builtin.include_role:
        name: 'r_pufky.data.test'
        tasks_from: 'file.yml'
      vars:
        test_name: '{{ "Verify | test | " ~ item }}'
        test_file: '{{ item }}'
        test_owner: 'mox'
        test_group: 'root'
        test_mode: '0750'
        test_state: 'directory'
        test_diff: true
      loop:
        - '{{ mox___app._data_d }}'
        - '{{ mox___app._config_d }}'

- name: 'Verify'
  hosts: 'mox-config'
  gather_facts: false
  tasks:
    - name: 'Verify | import role variables'
      ansible.builtin.include_vars:
        file: '{{
            lookup("env", "MOLECULE_PROJECT_DIRECTORY") ~ "/vars/main.yml"
          }}'

    - name: '{{ "Verify | test | " ~ mox___app._var_d }}'
      ansible.builtin.include_role:
        name: 'r_pufky.data.test'
        tasks_from: 'file.yml'
      vars:
        test_name: '{{ "Verify | test | " ~ item }}'
        test_file: '{{ item }}'
        test_owner: 'mox'
        test_group: 'root'
        test_mode: '02750'
        test_state: 'directory'
        test_diff: true
      loop:
        - '{{ mox___app._data_d }}'
        - '{{ mox___app._config_d }}'
